### ISSUE TITLE
Add Support for Custom MIDI Packs

### ISSUE THREAD

**Issue by OmegaZeroXIII** [vanessakindell/wadsmoosh-plus#17]
I thought it would be a good idea to add support for the different midi packs that are available to change the ones that sound in some maps like the Plutonia MIDI Pack for Plutonia, Master Levels for Doom II 25th Anniversary MIDI Pack for Master Levels and so on.

I leave as a reference the Plutonia MIDI Pack page so you can see the ones for the other WADs.

https://doomwiki.org/wiki/Plutonia_MIDI_Pack

**Comment by vanessakindell** [comment]
As it is now, there's no way to add these midi packs without breaking support for those wads if you don't have them. This is because it would require editing the mapinfo lump differently depending on if they exist or not. It's not impossible to do but it would require a lot of extra work that I'm simply not motivated to put in. However, if you fork the dev branch, do the work and make sure it doesn't break anything and submit a pull request, I'd be happy to merge it.
